### ISSUE TITLE
Initialisation of the graph for P2H results in incalculable graph

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/atlas#46]
In an attempt to resolves the issues https://github.com/quintel/etdataset/issues/607 and https://github.com/quintel/etsource/issues/921#issuecomment-108346139, I introduced and renamed several shares and updated the edges accordingly.

**A little background**

After we merged [this pull request](https://github.com/quintel/etsource/pull/923) the P2H node plays a very similar role in fulfilling the hot water demand as the add-on heat pump does in fulfilling the space heating demand. I therefore tried to replicate the add-on heat pump situation for the P2H node. Below is a screenshot of the graph (on BETA) and the initial shares that are defined for this part of the graph including their values (space heating in RED, hot water in BLUE and the shared solar water heater in green).

**The issue**

The space heating part of the graph (RED) shown below contains enough information to initialise the graph (as it always did). Interestingly, the hot water part (BLUE) contains the same amount of information, but results in incalculable parts of the graph when I run `rake debug` on Atlas. My guess was that this has to do with the righthand share of the blue part being `1-0`. I changed this to `0.999-0.001` and this indeed resulted in a fully initialised graph with correct results.

**The question**

@antw, do you know why the `1-0` share results in an incalculable graph and how we can best resolve this? I would like to resolve this before the September deploy.

**NB**

I have only updated the shares for the NL dataset as doing it for all is quite tedious work. Any failing specs associated with other datasets are thus to be expected and I will resolve those once this issue is resolved.

<img width="553" alt="screen shot 2015-08-25 at 17 03 13" src="https://cloud.githubusercontent.com/assets/4669028/9470844/14e38ebc-4b4e-11e5-9992-a99611419ec8.png">

Including @ChaelKruip .

**Comment by jorisberkhout** [comment]
BTW, my efforts so far are on this branch https://github.com/quintel/etsource/tree/p2h_shares

**Comment by jorisberkhout** [comment]
Moving to next deploy as we are not including storage in this one just yet.

**Comment by antw** [comment]
The main difference I'm noticing between `master` and `p2h_shares` is on the following edge:

![screen-shot-2015-10-01-at-15 49 10](https://cloud.githubusercontent.com/assets/4383/10224161/9603f96e-6854-11e5-9d35-dc2e65ac5332.png)

* [On master](https://github.com/quintel/etsource/blob/c866f7f21adad00c4dc59d51ad5d25cc33ee93bb/edges/households/households_useful_demand_for_hot_water_after_solar_heater_and_p2h-households_useful_demand_for_hot_water_for_houses_with_p2h%40useable_heat.ad)
* [On p2h_shares](https://github.com/quintel/etsource/blob/89472ab07e552521b1bb37987e6dc86a6f4750be/edges/households/households_useful_demand_for_hot_water_after_solar_heater_and_p2h-households_useful_demand_for_hot_water_for_houses_with_p2h%40useable_heat.ad)

Both branches define a `child_share`, but the `parent_share` is not present on the "p2h_shares" branch. If I add a `parent_share`, the graph becomes calculable.

Note that on the space heating side of the graph, there's a similar edge which has both parent and child shares:

![untitled-1](https://cloud.githubusercontent.com/assets/4383/10224505/34aec6b0-6856-11e5-8833-2e48f24844ed.png)

**Comment by jorisberkhout** [comment]
Thanks for sorting this out @antw . I have added the required parent share to fix this in a2da08985bde0f3b30c66448797f12ba3e226cc6. Closing this issue.
