### ISSUE TITLE
Undefined method 'captures' for NilClass.

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#48]
Atlas throws a really undescriptive error [on this line](https://github.com/quintel/atlas/blob/master/lib/atlas/parser/text_to_hash/block/multi_line_block.rb#L10), when somebody formats his or her query wrongly (\*cough, @RobTerwel\*). For instance

````
- query = EACH(
````

throws an error.

````
- query =
   EACH(
````

Doesn't.

It would be practical if a little more descriptive error is thrown stating that you can't do this and in which file this error occurs.

**Comment by antw** [comment]
Booya!

```
Atlas::InvalidMultilineBlockError: Invalid start to a multi-line attribute. The
value must start on the line following the equals ('=') sign.

  - query = V(
      energy_power_wind_turbine_coastal,total_land_use
    )

Occurred in: gqueries/general/area/area_used_for_coastal_wind.gql
```

The reason for this is if the lines following the attribute name (`- query`) are improperly indented, the parser can't tell the difference between single- and multi-line attributes.

For example:

```
- value = SUM(
DEMAND(one),
DEMAND(two)
)
```

Is that a multi-line attribute containing `SUM(DEMAND(one), DEMAND(two))`, or a single-line attribute with `SUM(` and three invalid lines thereafter? That's a hard problem for the (simple) parser to solve, even though it is obvious to we humans. 😉 

It *can* figure it out if the lines are indented properly:

```
- value = SUM(
    DEMAND(one),
    DEMAND(two)
  )
```

... and I quite like that, but it will require a more advanced parser to pick up incorrectly indented lines and raise a useful error message. I think I prefer to keep it strict – and consistent – by requiring that the value start on the line *after* the attribute name:

```
- value =
    SUM(
      DEMAND(one),
      DEMAND(two)
    )
```
