### ISSUE TITLE
Dumping the graph yml causes an error in the specs

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#56]
Here's what I came up with for dumping the `graph` YAML. Technically:

```ruby
Runner.new(@dataset, GraphBuilder.new.graph).calculate

# And than transform this to a YAML file probably :) but first:
```

Still when I try to execute this I get an error based on the `fixtures`:

````
   Refinery::IncalculableGraphError:
       Insufficient data to calculate 1 items:

         * NodeDemand for #<Refinery::Node key=:my_residence>
````

How to resolve this?

**Comment by grdw** [comment]
@jorisberkhout came with the suggestion to probably make an edge between this node and another 👼 and that works. Because now I'm getting different errors. Thanks!

**Comment by antw** [comment]
If I recall correctly, the Atlas fixtures are not intended to be passed into Refinery for calculation. There is not enough data for it to succeed (missing demands), nor is it guaranteed to be consistent (resulting in validation errors post-calculation). They exist only to assert that ActiveDocument classes work, and the graph *setup* code does the right thing.

Tests which use a post-Refinery graph [build that graph manually](https://github.com/quintel/atlas/blob/master/spec/atlas/exporter_spec.rb).
