### ISSUE TITLE
Which CSV files need to be scaled along with the local dataset?

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#63]
I'm not sure what to scale in order to create a full correct local dataset. I now only scale the attributes of a dataset which have the `proportional: true` flag in the attributes. But I'm not sure that's all you need to scale. 

This is assuming that you already scaled the exported `demands`, `max_demands`, etc. from the `graph.yml`.

**Comment by antw** [comment]
Probably none of them. Files from `load_profiles`, `fce`, and `network` are used in ETEngine, but the values contained in these files are relative to demand, not actual demands themselves. Therefore, I expect the files from the national dataset would also apply to any derived dataset.

**Comment by grdw** [comment]
> Probably none of them.

@ploh do the time curves really need to be scaled? I was just wondering that yesterday after our morning standup.

**Comment by ploh** [comment]
> do the time curves really need to be scaled?
I think so. They are scaled in the ETEngine scenario scaling as well.

**Comment by grdw** [comment]
[I think so to](https://github.com/quintel/etengine/blob/master/app/models/scenario_scaling.rb#L75) 👍
