### ISSUE TITLE
Explore initial inputs

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#71]
As described [here](https://github.com/quintel/internal/blob/master/planning/projects/local-datasets/stage0.md#step-b-adjust-a-deriveddataset-to-local-circumstances) it should be possible to change the local dataset to the circumstances as they exist in that certain municipality/city/area. To do this we had the idea to adjust values using "initializer inputs" (the queries that live inside of, `adjust_scaling/**/*.ad` files). 

My question:

**Should it be possible to overwrite anything in the graph?**

We export the "sparse graph" (i.e. the graph before refinery calcultates the rest of the demands). Should it therefor only be possible to alter parts of the sparse graph? The upsides to this approach is that refinery will calculate a *valid* graph in the end (so, there won't be any calculation errors). The downside is that the level of control you have over the graph is entirely determined by refinery and demands might trickle down in a way that's not desired [? if that's even a thing]. 

When you *can* alter anything in the graph (assuming therefor that the graph is first fully calculated in Refinery and than these 'edits' are overwriting the values in the graph) the downside is that Refinery has a chance of not calculating correctly (i.e. demands might not add up in combination with the shares etc.). This can be fixed by expanding the validate task in Atlas and make sure that everyting runs as planned when these initial inputs are set (so set initial input of x, run `rake validate <OPTIONS/>` and repeat). The upside is that you'd have more control over the graph. Than again you probably need to edit a lot of shares and nodes manually when changing the demand of a certain node in the middle of the fully calculated graph.

**Comment by ploh** [comment]
The initializer_inputs are _very_ similar to scenario's user_values in their application, i.e. they are applied after the MsgPacked-graph is loaded into ETEngine.

**Comment by antw** [comment]
@ploh is correct. Initializer inputs [will be applied in ETEngine](https://github.com/quintel/etengine/blob/69327792354a294a7f6a2b89f165c478b147f4bd/app/models/gql/gql.rb#L267-L268), so they won't impact Atlas+Refinery. ETEngine should have no trouble with this, as they'd be treated much like a normal input.

**Comment by grdw** [comment]
Ok. Makes sense 👍
