### ISSUE TITLE
Overview issue local datasets

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#78]
We're nearing the end of the [stage0](https://github.com/quintel/internal/blob/master/planning/projects/local-datasets/stage0.md) phase of the local dataset project. The [scaling](https://github.com/quintel/atlas/pull/77#discussion_r95540466) is being reviewed as we speak and the basic implementation of the initializer inputs is in a [pull request](https://github.com/quintel/etengine/pull/894) as well.

After both these pull requests are merged I think we need @DorinevanderVlies to test this locally on her machine to see if the workflow makes sense and if anything odd comes up.

Open todo (in somewhat prioritized order):

Refer to [planning document](https://github.com/quintel/internal/blob/master/planning/projects/local-datasets/planning.md)

**Comment by ChaelKruip** [comment]
@ploh do you think @grdw's estimates are realistic?

Including @DorinevanderVlies @dennisschoenmakers @AlexanderWirtz @jorisberkhout

**Comment by ploh** [comment]
> do you think @grdw's estimates are realistic?

Yes, and I have added rough estimates for the other points as well.

**Comment by ploh** [comment]
@grdw @ChaelKruip Just a very naive question: Why did we abandon the [planning document](https://github.com/quintel/internal/blob/master/planning/projects/local-datasets/planning.md) in favor of this here? I kind of miss the change tracking that we had there :slightly_frowning_face:

**Comment by ChaelKruip** [comment]
> @grdw @ChaelKruip Just a very naive question: Why did we abandon the planning document in favor of this here?

I don't think we have to abandon it. What I asked @grdw to do is to prioritise deliverables and assign expected times to them. The planning document already has a different structure. @ploh can you make it consistent with the list above though?

**Comment by ploh** [comment]
>  @ploh can you make it consistent with the list above though?

I transferred this to the planning document - only for the history though.
