### ISSUE TITLE
Testing of local datasets implementation

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#79]
**Cases:**

1. Test scaling with `rake scale` (does it make sense, if not why etc.)
2. Create a scenario from ETModel
3. Change any number in the scaled ad file (test if it changes the numbers in ETModel).
4. Change an initializer input (test if it changes the numbers in ETModel)
...

**Feedback:**

**Comment by ploh** [comment]
@DorinevanderVlies @grdw Can this be closed?

**Comment by DorinevanderVlies** [comment]
Yes. I've done some testing. I think it will be @BerendSmits who will work with local datasets next. If he comes across any issues I think he can make individual tickets for them.

**Comment by BerendSmits** [comment]
Yes I will, thanks
