### ISSUE TITLE
Remove Dataset from names of FullDataset and DerivedDataset

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#88]
From: https://github.com/quintel/atlas/pull/87#discussion_r98227238

> How would you guys feel about naming these two new classes simply "Derived" and "Full"? "Dataset" already appears in the module tree, and it would shorten the .ad file names ("datasets/nl/nl.full.ad" instead of "datasets/nl/nl.full_dataset.ad").

---

- [x] Rename classes in Atlas
- [x] Rename files in ETSource

For the sake of consistency should the `rake scale` task also be taking `FULL` and `DERIVED` as arguments? Or should they still be called `FULL_DATASET`. I personally think that the `_DATASET` suffix provides some more context than just `FULL`.

**Comment by ploh** [comment]
The rake arguments should stay because they are simply env variables and we do not want them set accidentally to anything

**Comment by ploh** [comment]
@grdw yes please, pick this up.
