### ISSUE TITLE
Derived datasets should be expanded with a GM_CODE, BU_CODE, WK_CODE

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#94]
In regards to https://github.com/quintel/etlocal/issues/33 the existing derived datasets should be expanded with a few bits of information in order to be functional with the map I created on etlocal. 

This is the map as it currently is:

![screen shot 2017-03-21 at 10 22 22](https://cloud.githubusercontent.com/assets/2676542/24140428/4ec38d12-0e20-11e7-81e6-f1bc18a47f3e.png)

The map shows you every municipality of the Netherlands. If you zoom in further it will show you the districts in that municipality and when you zoom in further you'll see the specific neighborhoods. The information to which municipality/district/neighborhood is available on a mouse-click. This raises the following issue: because the chart now lives independently of every dataset and is unaware which of them even exist, the existing datasets should be expanded with a few attributes. 

The following attributes must/might be added:

```ruby
# de_Biezen.ad

- area = de_Biezen
- municipality_code = GM0001
- neighborhood_code = BU0001
- district_code = WK0001

# Optional:
- province = ?
- center = [1.000, 1.000] # Lat,Lng
...
```

If anybody has better ideas, please say so. Keep in mind that this will only work for derived datasets of the Netherlands and not for Germany for that matter for their municipality/district coding-system might be totally different. 

Also I think we should use these codes as a folder structure. Or something like this:

```
nl
-- drenthe
-- groningen
---- <GM_CODE> - <GM_NAAM>
------ <WK_CODE> - <WK_NAAM>
-------- <BU_CODE> - <BU_NAAM>
```

Than again, raising this: https://github.com/quintel/etsource/issues/1180

**Comment by AlexanderWirtz** [comment]
@grdw this looks viable to me. I think the `country` and `province` attributes are probably not optional. We need to be able to relate datasets to their parents as well, if you ask me. This might help in selecting provinces first, municipalities second etc.

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/atlas/blob/master/lib/atlas/dataset/derived.rb#L8
